/**
 * CAMPUS 6.0 — Premium Study Tips Collection
 * ৩টা+ bonus admission tips — daily rotate + push notification
 */

export interface StudyTip {
  id: number;
  title: string;
  body: string;
  emoji: string;
  category: 'recall' | 'strategy' | 'mindset' | 'technique';
}

export const PREMIUM_STUDY_TIPS: StudyTip[] = [
  { id: 1, emoji: '📓', category: 'technique',
    title: 'ভুলের খাতা',
    body: 'শুধু পড়লে হবে না, যে প্রশ্নগুলো ভুল হচ্ছে সেগুলো আলাদা খাতায় লিখে রাখো। শেষ সময়ে এই খাতাই সবচেয়ে বেশি কাজে দেবে।' },
  { id: 2, emoji: '🔄', category: 'strategy',
    title: 'Revision First',
    body: 'নতুন chapter শেষ করার চেয়ে আগের পড়া ভুলে না যাওয়াটা বেশি গুরুত্বপূর্ণ। প্রতিদিন অন্তত কিছু সময় revision-এর জন্য রাখো।' },
  { id: 3, emoji: '📚', category: 'strategy',
    title: 'Question Bank is Gold',
    body: 'শুধু বই পড়ে প্রস্তুতি নিও না। Previous Year প্রশ্ন সমাধান করো—কোন topic বারবার আসছে সেটা বুঝতে পারবে।' },
  { id: 4, emoji: '🧠', category: 'recall',
    title: 'Active Recall',
    body: 'বই বন্ধ করে নিজেকে প্রশ্ন করো: "আমি কী মনে রাখতে পেরেছি?" পড়া দেখে চিনতে পারা আর নিজে থেকে বলতে পারা এক জিনিস নয়।' },
  { id: 5, emoji: '⏱️', category: 'technique',
    title: 'Timer দিয়ে MCQ',
    body: 'Practice করার সময় সবসময় untimed practice কোরো না। নির্দিষ্ট সময়ের মধ্যে MCQ solve করার অভ্যাস গড়ে তুলো।' },
  { id: 6, emoji: '🎯', category: 'strategy',
    title: 'Easy First',
    body: 'পরীক্ষায় প্রথমেই কঠিন প্রশ্নে আটকে থেকো না। আগে যেগুলো নিশ্চিতভাবে পারো সেগুলো secure করো।' },
  { id: 7, emoji: '⚠️', category: 'strategy',
    title: 'Negative Marking মাথায় রাখো',
    body: 'শুধু বেশি প্রশ্ন attempted করাই লক্ষ্য নয়। Accuracy গুরুত্বপূর্ণ—বিশেষ করে negative marking থাকলে।' },
  { id: 8, emoji: '📊', category: 'technique',
    title: 'Daily MCQ Target',
    body: 'প্রতিদিন নির্দিষ্ট সংখ্যক MCQ solve করার লক্ষ্য রাখো। ধারাবাহিকতা একদিনে ৫০০ প্রশ্ন করার চেয়ে বেশি powerful।' },
  { id: 9, emoji: '✍️', category: 'recall',
    title: 'পড়া নয়, Recall',
    body: 'একটি topic পড়ার ২০–৩০ মিনিট পর বই বন্ধ করে সেটার মূল points নিজে লিখে ফেলো। কোথায় gap আছে সঙ্গে সঙ্গে ধরা পড়বে।' },
  { id: 10, emoji: '⚔️', category: 'mindset',
    title: 'Weak Topic Attack',
    body: 'যে chapter বারবার এড়িয়ে যাচ্ছো, সেটাই তোমার rank কমানোর কারণ হতে পারে। প্রতিদিন অন্তত একটি weak topic tackle করো।' },
  { id: 11, emoji: '🔍', category: 'technique',
    title: 'একই ভুল দুইবার নয়',
    body: 'একই ধরনের প্রশ্ন দ্বিতীয়বার ভুল হলে শুধু answer দেখো না—কেন ভুল হয়েছিল সেটা খুঁজে বের করো।' },
  { id: 12, emoji: '📈', category: 'strategy',
    title: '3-Level Revision',
    body: 'প্রথম revision দ্রুত, দ্বিতীয় revision প্রশ্নভিত্তিক, তৃতীয় revision শুধু ভুল ও high-yield information দিয়ে করো।' },
  { id: 13, emoji: '🎓', category: 'technique',
    title: 'Mock Test আসল পরীক্ষা',
    body: 'Mock test-কে practice হিসেবে নয়, আসল admission exam হিসেবে দাও। নির্দিষ্ট সময়, no phone, no break।' },
  { id: 14, emoji: '📝', category: 'technique',
    title: 'Mock Analysis',
    body: 'Mock test দেওয়ার চেয়ে test analysis বেশি গুরুত্বপূর্ণ। ভুল + guessed + time-consuming প্রশ্নগুলো আলাদা করে review করো।' },
  { id: 15, emoji: '🎲', category: 'strategy',
    title: 'Guessing Strategy',
    body: 'সব MCQ-তে guess করা বুদ্ধিমানের কাজ নয়। Options eliminate করতে পারলে তবেই calculated guess করো।' },
  { id: 16, emoji: '📒', category: 'technique',
    title: 'Smart Notes',
    body: 'বইয়ের পুরো chapter আবার লিখে ফেলো না। Formula, exception, confusing facts, ভুল প্রশ্ন—শুধু এগুলো note করো।' },
  { id: 17, emoji: '🎯', category: 'mindset',
    title: 'পড়ার আগে Target',
    body: '"আজ অনেক পড়ব" বলার বদলে বলো—"আজ Chemistry 2nd chapter + 100 MCQ + ভুলগুলো revise করব।"' },
  { id: 18, emoji: '📵', category: 'mindset',
    title: 'Phone দূরে রাখো',
    body: 'Admission preparation-এর সবচেয়ে বড় silent enemy অনেক সময় কঠিন chapter নয়—একটা notification। Study session-এ phone physically দূরে রাখো।' },
  { id: 19, emoji: '⏰', category: 'technique',
    title: '50/10 Focus',
    body: '৫০ মিনিট গভীরভাবে পড়ো, তারপর ১০ মিনিট break নাও। Break-এ social media খুললে focus নষ্ট হওয়ার সম্ভাবনা বেশি।' },
  { id: 20, emoji: '📋', category: 'technique',
    title: 'পড়ার Sequence',
    body: 'একটি ভালো sequence হতে পারে: Concept → Practice → Mistake Analysis → Revision। শুধু lecture দেখে থেমে যেও না।' },
  { id: 21, emoji: '🧮', category: 'recall',
    title: 'Formula প্রয়োগ',
    body: 'Formula পড়ার সঙ্গে সঙ্গে অন্তত কয়েকটি problem solve করো। প্রয়োগ ছাড়া formula পরীক্ষার হলে ভুলে যেতে পারো।' },
  { id: 22, emoji: '🔁', category: 'recall',
    title: 'Spaced Revision',
    body: 'শুধু একবার পড়ে ছেড়ে দিও না। ছোট ছোট spaced revision দিলে factual information অনেক বেশি সময় মনে থাকে।' },
  { id: 23, emoji: '📖', category: 'technique',
    title: 'English Vocabulary',
    body: 'প্রতিদিন ১০–১৫টি শব্দ শিখে পরদিন, ৩ দিন পর এবং ১ সপ্তাহ পর আবার revise করো। একদিনে ১০০টি শব্দ শেখার চেয়ে এটা বেশি effective।' },
  { id: 24, emoji: '🌐', category: 'strategy',
    title: 'Current Affairs Smartly',
    body: 'সব খবর পড়ার দরকার নেই। বাংলাদেশ, আন্তর্জাতিক গুরুত্বপূর্ণ ঘটনা, বিজ্ঞান-প্রযুক্তি, পুরস্কার, খেলাধুলা ও পরীক্ষায় আসার সম্ভাবনাময় তথ্যকে priority দাও।' },
  { id: 25, emoji: '🎯', category: 'strategy',
    title: 'Department নয়, Unit বুঝো',
    body: 'Admission preparation-এ শুধু subject selection নয়, কোন unit-এ কোন ধরনের question আসে সেটাও আগে বুঝে strategy বানাও।' },
  { id: 26, emoji: '💪', category: 'mindset',
    title: 'Cutoff-এর পেছনে নয়',
    body: '"কত নম্বর পেলে হবে?"—এটার চেয়ে "আমি কীভাবে নিজের score সর্বোচ্চ করতে পারি?" এই প্রশ্নটা বেশি useful।' },
  { id: 27, emoji: '🔄', category: 'recall',
    title: 'একই Topic বারবার দেখা',
    body: 'একটি topic আজ পড়ো, কয়েকদিন পর আবার recall করো। Long-term memory তৈরি হয় repetition দিয়ে, একবার পড়ে নয়।' },
  { id: 28, emoji: '😴', category: 'mindset',
    title: 'Sleep is Preparation',
    body: 'শেষ রাতে অতিরিক্ত পড়ে ঘুম নষ্ট করে পরদিন exam hall-এ tired হয়ে যেও না। ভালো preparation-এর অংশই হলো পর্যাপ্ত ঘুম।' },
  { id: 29, emoji: '🙈', category: 'mindset',
    title: 'Rank তুলনা বন্ধ',
    body: 'অন্যজন দিনে ১২ ঘণ্টা পড়ে কিনা সেটা তোমার score বাড়াবে না। নিজের গতকালের performance-এর সঙ্গে আজকের performance compare করো।' },
  { id: 30, emoji: '💥', category: 'mindset',
    title: 'Bad Day ≠ Bad Preparation',
    body: 'একদিন target পূরণ না হলে পুরো routine ভেঙে দিও না। পরের session থেকেই আবার শুরু করো।' },
  { id: 31, emoji: '🏁', category: 'strategy',
    title: 'শেষ ৩০ দিন',
    body: 'শেষ সময়ে নতুন source বাড়ানোর বদলে revision, question bank, mock test এবং ভুলের খাতাকে priority দাও।' },
  { id: 32, emoji: '📕', category: 'strategy',
    title: 'Source কমাও',
    body: 'একই topic-এর জন্য ৪টা বই, ৩টা PDF, ৫টা YouTube channel ব্যবহার করলে confusion বাড়তে পারে। একটি reliable source + question practice যথেষ্ট।' },
  { id: 33, emoji: '🌙', category: 'recall',
    title: 'One-Day Rule',
    body: 'আজ যা পড়েছো, দিনের শেষে ১০–১৫ মিনিট সেটার quick recall করো। এই ছোট অভ্যাস retention অনেক বাড়াতে পারে।' },
  { id: 34, emoji: '📝', category: 'strategy',
    title: 'Exam Hall Strategy',
    body: 'প্রথম কয়েক মিনিট panic না করে question pattern এবং নিজের time allocation ঠিক করে নাও।' },
  { id: 35, emoji: '⚡', category: 'mindset',
    title: 'Consistency Beats Motivation',
    body: 'প্রতিদিন motivation আসবে না। Admission preparation সফল হয় motivation দিয়ে শুরু করে discipline দিয়ে চালিয়ে গেলে।' },
  { id: 36, emoji: '🎯', category: 'mindset',
    title: 'আজকের 1%',
    body: 'আজ পুরো syllabus শেষ করার চিন্তা করো না। আজকের একটি chapter, একটি mock, একটি ভুলের analysis—এভাবেই বড় preparation তৈরি হয়।' },
];

/** দিন অনুযায়ী আজকের tip */
export const getTodayTip = (): StudyTip => {
  const d = new Date();
  const start = new Date(d.getFullYear(), 0, 0);
  const doy = Math.floor((d.getTime() - start.getTime()) / 86400000);
  return PREMIUM_STUDY_TIPS[doy % PREMIUM_STUDY_TIPS.length];
};