export const SYLLABUS_DATA: any = {
  SSC: {
    "Physics": ["ভৌত রাশি ও পরিমাপ (Physical Quantities and Measurement)", "গতি (Motion)", "বল (Force)", "কাজ, ক্ষমতা ও শক্তি (Work, Power and Energy)", "পদার্থের অবস্থা ও চাপ (State of Matter and Pressure)", "বস্তুর উপর তাপের প্রভাব (Effect of Heat on Matter)", "তরঙ্গ ও শব্দ (Waves and Sound)", "আলোর প্রতিফলন (Reflection of Light)", "আলোর প্রতিসরণ (Refraction of Light)", "স্থির তড়িৎ (Static Electricity)", "চল তড়িৎ (Current Electricity)", "বিদ্যুতের চৌম্বক ক্রিয়া (Magnetic Effect of Current)", "আধুনিক পদার্থবিজ্ঞান ও ইলেকট্রনিক্স (Modern Physics and Electronics)"],
    "Chemistry": ["রসায়নের ধারণা (Concept of Chemistry)", "পদার্থের অবস্থা (States of Matter)", "পদার্থের গঠন (Structure of Matter)", "পর্যায় সারণি (Periodic Table)", "রাসায়নিক বন্ধন (Chemical Bonds)", "মোলের ধারণা ও রাসায়নিক গণনা (Concept of Mole and Chemical Counting)", "রাসায়নিক বিক্রিয়া (Chemical Reactions)", "রসায়ন ও শক্তি (Chemistry and Energy)", "এসিড-ক্ষারক সমতা (Acid-Base Balance)", "খনিজ সম্পদ: ধাতু-অধাতু (Mineral Resources: Metals and Non-metals)", "খনিজ সম্পদ: জীবাশ্ম (Mineral Resources: Fossils)"],
    "Higher_Math": ["সেট ও ফাংশন (Sets and Functions)", "বীজগণিতীয় রাশি (Algebraic Expressions)", "জ্যামিতি (Geometry)", "সমীকরণ (Equations)", "অসমতা (Inequalities)", "অসীম ধারা (Infinite Series)", "ত্রিকোণমিতি (Trigonometry)", "সূচকীয় ও লগারিদমীয় ফাংশন (Exponential and Logarithmic)", "দ্বিপদী বিস্তৃতি (Binomial Expansion)", "স্থানাঙ্ক জ্যামিতি (Coordinate Geometry)", "সমতলীয় ভেক্টর (Planar Vectors)", "সম্ভাবনা (Probability)"],
    "Biology": ["জীবন পাঠ (Lessons on Life)", "জীবকোষ ও টিস্যু (Cells and Tissues)", "কোষ বিভাজন (Cell Division)", "জীবনীশক্তি (Bioenergetics)", "খাদ্য, পুষ্টি এবং পরিপাক (Food, Nutrition and Digestion)", "জীবে পরিবহণ (Transport in Organisms)", "গ্যাসীয় বিনিময় (Gaseous Exchange)", "রেচন প্রক্রিয়া (Excretory System)", "দৃঢ়তা প্রদান ও চলন (Firmness and Movement)", "সমন্বয় (Coordination)", "জীবের প্রজনন (Reproduction)", "জীবের বংশগতি ও বিবর্তন (Heredity and Evolution)", "জীবের পরিবেশ (Environment of Life)"]
  },
  HSC: {
    "Physics_1st_Paper": ["ভৌত জগত ও পরিমাপ (Physical World and Measurement)", "ভেক্টর (Vector)", "গতিবিদ্যা (Dynamics)", "নিউটনীয় বলবিদ্যা (Newtonian Mechanics)", "কাজ, শক্তি ও ক্ষমতা (Work, Energy and Power)", "মহাকর্ষ ও অভিকর্ষ (Gravitation and Gravity)", "পদার্থের গাঠনিক ধর্ম (Structural Properties of Matter)", "পর্যাবৃত্ত গতি (Periodic Motion)", "তরঙ্গ (Waves)", "আদর্শ গ্যাস ও গ্যাসের গতিতত্ত্ব (Ideal Gas and Kinetics)"],
    "Physics_2nd_Paper": ["তাপগতিবিদ্যা (Thermodynamics)", "স্থির তড়িৎ (Static Electricity)", "চল তড়িৎ (Current Electricity)", "তড়িৎ প্রবাহের চৌম্বক ক্রিয়া ও চুম্বকত্ব (Magnetic Effects of Electric Current)", "তাড়িতচৌম্বক আবেশ ও পরিবর্তী প্রবাহ (Electromagnetic Induction)", "জ্যামিতিক আলোকবিজ্ঞান (Geometrical Optics)", "ভৌত আলোকবিজ্ঞান (Physical Optics)", "আধুনিক পদার্থবিজ্ঞানের সূচনা (Introduction to Modern Physics)", "পরমাণুর মডেল ও নিউক্লিয়ার পদার্থবিজ্ঞান (Atomic Models and Nuclear Physics)", "সেমিকন্ডাক্টর ও ইলেকট্রনিক্স (Semiconductor and Electronics)"],
    "Chemistry_1st_Paper": ["ল্যাবরেটরির নিরাপদ ব্যবহার (Safe Use of Laboratory)", "গুণগত রসায়ন (Qualitative Chemistry)", "মৌলের পর্যায়বৃত্ত ধর্ম ও রাসায়নিক বন্ধন (Periodic Properties and Chemical Bonds)", "রাসায়নিক পরিবর্তন (Chemical Changes)", "কর্মমুখী রসায়ন (Vocational Chemistry)"],
    "Chemistry_2nd_Paper": ["পরিবেশ রসায়ন (Environmental Chemistry)", "জৈব রসায়ন (Organic Chemistry)", "পরিমাণগত রসায়ন (Quantitative Chemistry)", "তড়িৎ রসায়ন (Electrochemistry)", "অর্থনৈতিক রসায়ন (Economic Chemistry)"],
    "Higher_Math_1st_Paper": ["ম্যাট্রিক্স ও নির্ণায়ক (Matrices and Determinants)", "ভেক্টর (Vector)", "সরলরেখা (Straight Lines)", "বৃত্ত (Circles)", "বিন্যাস ও সমাবেশ (Permutations and Combinations)", "ত্রিকোণমিতিক অনুপাত (Trigonometric Ratios)", "অন্তরীকরণ (Differentiation)", "যোগজীকরণ (Integration)"],
    "Higher_Math_2nd_Paper": ["বাস্তব সংখ্যা ও অসমতা (Real Numbers and Inequalities)", "যোগাশ্রয়ী প্রোগ্রামিং (Linear Programming)", "জটিল সংখ্যা (Complex Numbers)", "বহুপদী ও বহুপদী সমীকরণ (Polynomials and Equations)", "কনিক (Conics)", "বিপরীত ত্রিকোণমিতিক ফাংশন (Inverse Trigonometric Functions)", "স্থিতিবিদ্যা (Statics)", "গতিবিদ্যা (Dynamics)", "সমতলে বস্তুকণার গতি (Motion of Particles in a Plane)", "বিস্তার পরিমাপ ও সম্ভাবনা (Measures of Dispersion and Probability)"],
    "Biology_1st_Paper": ["কোষ ও এর গঠন (Cell and its Structure)", "কোষ বিভাজন (Cell Division)", "কোষ রসায়ন (Cell Chemistry)", "অণুজীব (Microorganisms)", "শৈবাল ও ছত্রাক (Algae and Fungi)", "ব্রায়োফাইটা ও টেরিডোফাইটা (Bryophyta and Pteridophyta)", "নগ্নবীজী ও আবৃতবীজী উদ্ভিদ (Gymnosperms and Angiosperms)", "টিস্যু ও টিস্যুতন্ত্র (Tissue and Tissue System)", "উদ্ভিদ শারীরতত্ত্ব (Plant Physiology)", "উদ্ভিদ প্রজনন (Plant Reproduction)", "জীবপ্রযুক্তি (Biotechnology)", "জীবের পরিবেশ, বিস্তার ও সংরক্ষণ (Environment, Distribution and Conservation)"],
    "Biology_2nd_Paper": ["প্রাণীর বিভিন্নতা ও শ্রেণিবিন্যাস (Animal Diversity and Classification)", "প্রাণীর পরিচিতি (Introduction to Animals)", "মানব শারীরতত্ত্ব: পরিপাক ও শোষণ (Human Physiology: Digestion)", "মানব শারীরতত্ত্ব: রক্ত ও সঞ্চালন (Blood and Circulation)", "মানব শারীরতত্ত্ব: শ্বাসক্রিয়া ও শ্বসন (Breathing and Respiration)", "মানব শারীরতত্ত্ব: বর্জ্য ও নিষ্কাশন (Waste and Excretion)", "মানব শারীরতত্ত্ব: চলন ও অঙ্গচালনা (Movement and Locomotion)", "মানব শারীরতত্ত্ব: সমন্বয় ও নিয়ন্ত্রণ (Coordination and Control)", "মানব জীবনের ধারাবাহিকতা (Continuity of Human Life)", "মানবদেহের প্রতিরক্ষা (Immunity)", "জিনতত্ত্ব ও বিবর্তন (Genetics and Evolution)", "প্রাণীর আচরণ (Animal Behavior)"]
  }
};
export const DAYS_OF_WEEK = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
export const SSC_SYLLABUS = SYLLABUS_DATA.SSC;
export const MONTHS = [
  "January", "February", "March", "April", "May", "June", 
  "July", "August", "September", "October", "November", "December"
];
export const WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const MASTER_SCHOLARS: any[] = [
  { id: "1", username: "Apex_Learner", email: "apex@aurobit.com", displayName: "Apex Learner", online: true },
  { id: "2", username: "CodeNinja", email: "ninja@aurobit.com", displayName: "Code Ninja", online: false },
  { id: "3", username: "Quantum_Mind", email: "quantum@aurobit.com", displayName: "Quantum Mind", online: true }
];
